name: AdvancedCommandBlocker
version: '1.0-SNAPSHOT'
main: com.maddyjace.advancedcommandblocker.AdvancedCommandBlocker
authors: [MaddyJace]
description: Prevent specific commands from being used
folia-supported: true
softdepend:
  - PlaceholderAPI

commands:
  advancedcommandblocker:
    description: Main plugin command.
    aliases: [acb,advancedcommandblocker]
    permission: advancedcommandblocker.admin

permissions:
  advancedcommandblocker.admin:
    description: Gives the player access to the main plugin command.
    default: op